config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  resources :profiles, only: [:show, :edit, :update, :index] do
    member do
      get 'following'
      get 'followers'
    end
  end

   # RESTful resources
   resources :posts do
    resource :like, only: [:create, :destroy]
    resources :post_interests, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      post 'like'
      delete 'unlike'
    end
    #   post 'share'
    #   delete 'unshare'
    # end
  end

  resources :chats, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  post "chats/create", to: 'chats#create', as: :create_chat

  resources :user_interests, only: [:create, :destroy]

  # User profiles and following functionality
  resources :users, only: [:index, :show] do
    member do
      post 'follow'
      delete 'unfollow'
    end
  end

  # collection do
  #   get 'feed'  # For showing the user's personalized feed
  # end

  resources :follows, only: [:index]

  resources :follows, only: [] do
    collection do
      get 'following'  # List of users you're following
      get 'followers'  # List of users who follow you
    end
  end

  # Interests
  resources :interests, only: [:index, :show] do
    member do
      post 'follow'    # For following an interest
      delete 'unfollow'  # For unfollowing an interest
    end
  end

  # Additional custom routes
  get 'explore', to: 'posts#explore'  # For discovering new content
  get 'trending', to: 'posts#trending'  # For trending posts
  get 'search', to: 'search#index'  # For search functionality


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-align">

      <%= link_to root_path, class: "" do %>
        <span class="tapthat">TapThat</span>
      <% end %>

      <% if user_signed_in? %>
        <div class="list nav dropdown">
          <ul>
            <!--<li class="list-items"><%#= image_tag("house-door.svg", height: "20px", width: "20px", class: "inverted") %><%= link_to 'Home', root_path, class: "list-items-text" %></li>-->
            <li class="list-items">
              <%= link_to root_path, class: "list-items-link" do %>
                <%= image_tag("house-door.svg", height: "20px", width: "20px", class: "inverted") %>
                <span class="list-items-text">Home</span>
              <% end %>
            </li>
            <!--<li class="list-items dropdown-item"><%#= image_tag("search.svg", height: "20px", width: "20px", class: "inverted") %><%= link_to 'Search', root_path, class: "list-items-text" %></li>-->
            <!--<li class="list-items"><%#= image_tag("compass.svg", height: "20px", width: "20px", class: "inverted") %><%= link_to 'Explore', interests_path, class: "list-items-text" %></li>-->
            <li class="list-items">
              <%= link_to interests_path, class: "list-items-link" do %>
                <%= image_tag("compass.svg", height: "20px", width: "20px", class: "inverted") %>
                <span class="list-items-text">Explore</span>
              <% end %>
            </li>
            <!--<li class="list-items"><%#= image_tag("inbox.svg", height: "20px", width: "20px", class: "inverted") %><%= link_to 'Inbox', chats_path, class: "list-items-text" %></li>-->
            <li class="list-items">
              <%= link_to chats_path, class: "list-items-link" do %>
                <%= image_tag("inbox.svg", height: "20px", width: "20px", class: "inverted") %>
                <span class="list-items-text">Inbox</span>
              <% end %>
            </li>
            <!--<li class="list-items"><%#= image_tag("plus-square.svg", height: "20px", width: "20px", class: "inverted") %><%= link_to 'New Post', new_post_path, class: "list-items-text" %></li>-->
            <li class="list-items">
              <%= link_to new_post_path, class: "list-items-link" do %>
                <%= image_tag("plus-square.svg", height: "20px", width: "20px", class: "inverted") %>
                <span class="list-items-text">New Post</span>
              <% end %>
            </li>

            <li class="list-items">
              <%= link_to profile_path(current_user), class: "list-items-link" do %>
                <%= image_tag("person-fill.svg", height: "20px", width: "20px", class: "inverted") %>
                <span class="list-items-text">Profile</span>
              <% end %>
            </li>


          </ul>
        </div>
      <% end %>

      <!-- Search Bar -->



  </div>
</div>