config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  resources :profiles, only: [:show, :edit, :update, :index] do
    member do
      get 'following'
      get 'followers'
    end
  end

   # RESTful resources
   resources :posts do
    resource :like, only: [:create, :destroy]
    resources :post_interests, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      post 'like'
      delete 'unlike'
    end
    #   post 'share'
    #   delete 'unshare'
    # end
  end

  resources :chats, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  post "chats/create", to: 'chats#create', as: :create_chat

  resources :user_interests, only: [:create, :destroy]

  # User profiles and following functionality
  resources :users, only: [:index, :show] do
    member do
      post 'follow'
      delete 'unfollow'
    end
  end

  # collection do
  #   get 'feed'  # For showing the user's personalized feed
  # end

  resources :follows, only: [:index]

  resources :follows, only: [] do
    collection do
      get 'following'  # List of users you're following
      get 'followers'  # List of users who follow you
    end
  end

  # Interests
  resources :interests, only: [:index, :show] do
    member do
      post 'follow'    # For following an interest
      delete 'unfollow'  # For unfollowing an interest
    end
  end

  # Additional custom routes
  get 'explore', to: 'posts#explore'  # For discovering new content
  get 'trending', to: 'posts#trending'  # For trending posts
  get 'search', to: 'search#index'  # For search functionality


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  after_commit :process_photo, on: :create
  # Posts associations
  # has_many :posts, dependent: :destroy


  # Likes associations
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  # Shares associations
  has_many :shares, dependent: :destroy
  has_many :shared_posts, through: :shares, source: :post

  # Follow associations
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :followed_users, source: :following

  has_many :following_users, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :following_users, source: :follower

  has_many :comments, dependent: :destroy

  # Interests associations
  # has_many :user_interests, dependent: :destroy
  # has_many :interests, through: :user_interests

  has_many :post_interests, dependent: :destroy
  has_many :interests, through: :post_interests

  accepts_nested_attributes_for :post_interests

  private

  def process_photo
    PhotoProcessingJob.perform_later(self.id) if photo.attached?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  def show
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user # Associate the post with the current user
    if @post.save
      PhotoProcessingJob.perform_later(@post.id) if @post.photo.attached?
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  def like
    @post = Post.find(params[:id])
    # Check if the user has already liked the post
    if current_user.likes.exists?(post: @post)
      render json: { error: "You have already liked this post." }, status: :unprocessable_entity
    else
      current_user.likes.create(post: @post)
      render json: { message: "You liked the post." }, status: :ok
    end
  rescue ActiveRecord::RecordNotFound
    render json: { error: "Post not found." }, status: :not_found
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :photo, interest_ids: [])
  end
end

app/views/posts/_form.html.erb
<div class="container">
  <div class="row justify-content-center">

    <div class="col-md-8">
      <div class="card shadow-sm">
        <div class="card-body">
          <%= simple_form_for @post do |f| %>
            <%= f.input :content,
                        label: 'Post Content',
                        input_html: { rows: 4, class: 'form-control' } %>
                        <div class="mb-3">

            <%= f.input :photo,
                                as: :file,
                                label: 'Upload Image',
                                input_html: { class: 'form-control' } %>
                        </div>

            <div class="mb-3">
              <%= f.association :interests,
                              as: :check_boxes,
                              collection: Interest.all,
                              label: 'Select Interests',
                              include_blank: false,
                              input_html: { class: 'form-check-input' },
                              item_wrapper_class: 'form-check mb-2',
                              wrapper_html: { class: 'border rounded p-3' } %>
            </div>

            <%= f.button :submit, class: 'btn btn-primary w-100' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="shift-250 edit">
<h1>Edit Post</h1>
<%= render 'form' %>
<div class="pt-4">
  <%= link_to 'Back to Posts', posts_path, class: 'btn btn-primary' %>
</div>
</div>

app/views/posts/index.html.erb
<div class="shift-250 pt-2">
<div class="container justify-content-center down">
<div class="row justify-content-center px-3">
        <div class="justify-content-center search-bar col-md-6 col-lg-6 wide photo-container there">
          <% if user_signed_in? %>

          <div class="col-sm-50 my-8 pad">
            <%= form_with url: profiles_path, method: :get, class: "search-form" do %>
              <div class="input-group">

                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control search-input search-height",
                  placeholder: "type a name"
                %>

                <div class="input-group-append search-button submit">
                  <%= submit_tag "Search", name: "", class: "btn btn-primary search-btn submit" %>
                </div>

              </div>
            <% end %>
          </div>
          <% end %>
        </div>

        </div>

  <div class="row justify-content-center single mt-3 rowwy px-3">

    <% @posts.each do |post| %>
      <div class="col-md-6 col-lg-6 mb-4 wide photo-container">
        <div class=" shadow-sm bg-light photo-container-crop">
          <% if post.photo.attached? %>
            <div class="image-container">
            <%= cl_image_tag post.photo.key, height: 450, width: 300, class: "constrain-image photo" %>
            <div class="image-overlay"></div>
            </div>
          <% else %>
            <div class="card-img-top bg-light d-flex align-items-center justify-content-center" style="height: 300px;">
              <p class="text-muted">No media available unfortunately my guy</p>
            </div>
          <% end %>

          <div class="card-body overlay">
          <div class="right-corner">
          <div class="like-comment-share">

            <!-- Like, Comment, Share, Edit Icons -->
<div class="d-flex justify-content-between align-items-center mb-2">
  <div class="d-flex align-items-center gap-3">
    <!-- Like Icon -->
    <div id="<%= dom_id(post, :like) %>" data-controller="like" data-like-post-id-value="<%= post.id %>" data-like-liked-value="<%= user_signed_in? && current_user.likes.exists?(post: post) %>">
      <i class="fa fa-heart <%= user_signed_in? && current_user.likes.exists?(post: post) ? 'liked text-danger' : '' %>" data-action="click->like#toggleLike" style="cursor: pointer; font-size: 1.2rem;"></i>
    </div>

    <!-- Comment Icon -->
    <a href="#" class="text-dark" data-bs-toggle="collapse" data-bs-target="#comments-<%= post.id %>" title="Comments">
      <i class="fa fa-comment" style="font-size: 1.2rem;"></i>
    </a>

    <!-- Share Icon -->
    <a href="#" class="text-dark" data-bs-toggle="collapse" data-bs-target="#share-<%= post.id %>" title="Share">
      <i class="fa fa-share" style="font-size: 1.2rem;"></i>
    </a>
  </div>

  <!-- Edit Icon (Moved to Far Right) -->
  <% if user_signed_in? && post.user == current_user %>
    <a href="<%= edit_post_path(post) %>" class="text-dark ms-auto" title="Edit">
      <i class="fa fa-edit" style="font-size: 1.2rem;"></i>
    </a>
  <% end %>
</div>

            <div class="collapse mt-3 showy" id="comments-<%= post.id %>">
              <%= form_with(model: [post, Comment.new], local: false) do |form| %>
                <div class="input-group mb-2">
                  <%= form.text_field :content, placeholder: "Write a comment...", class: "form-control" %>
                  <%= form.submit "Post", class: "btn btn-primary" %>
                </div>
              <% end %>

              <% post.comments.order(created_at: :desc).each do |comment| %>
                <div class="mb-2">
                  <strong><%= comment.user.username %>:</strong>
                  <%= comment.content %>
                  <small class="text-muted d-block"><%= time_ago_in_words(comment.created_at) %> ago</small>
                </div>
              <% end %>
            </div>

            <!-- Share Section -->
            <div class="collapse" id="share-<%= post.id %>">
              <div class="d-flex justify-content-around">
                <a href="https://www.facebook.com/sharer/sharer.php?u=<%= post_url(post) %>" target="_blank" class="btn btn-sm btn-primary">
                  <i class="fab fa-facebook-f"></i> Facebook
                </a>

                <a href="https://www.linkedin.com/sharing/share-offsite/?url=<%= post_url(post) %>" target="_blank" class="btn btn-sm btn-secondary">
                  <i class="fab fa-linkedin-in"></i> LinkedIn
                </a>
                <a href="https://wa.me/?text=<%= CGI.escape(post_url(post)) %>" target="_blank" class="btn btn-sm btn-success">
                  <i class="fab fa-whatsapp"></i> WhatsApp
                </a>
              </div>
            </div>
          </div>

            <p class="card-text text-muted mb-2">
              <div class="posted">
                <strong><%= link_to "@#{post.user.username}", profile_path(post.user) %></strong>
                <%= post.content %><br>
              </div>
              <div class="posted-by"><%= post.interests.map { |interest| "##{interest.title}" }.join(", ") %></div>
              <div class="posted-by"><%= post.created_at.strftime("%B %d, %Y") %></div>
            </p>

</div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<div class="container pb-5 mb-5">
  <div class="shift-250">
    <div class="flexing-header-post">
      <h1 class="fw-bolder">New Post</h1>
      <%= link_to 'Back to Posts', posts_path, class: 'btn btn-primary' %>
    </div>
    <%= render 'form' %>
  </div>
</div>